67P/hyperchannel

app/components/message-chat-me/component.js
app/components/message-chat-me/template.hbs
app/components/message-chat/component.js
app/controllers/space/base_channel.js
app/services/smt.js
app/styles/app.scss
app/styles/components/message-chat.scss

Add support for /me command

---

app/components/channel-nav/template.hbs
app/models/space.js
tests/unit/models/space-test.js

Refs #45 
@galfert Would you add a test for something like this?

Sort the channels in the sidebar

---

.jshintrc
app/components/channel-container/template.hbs
app/models/channel.js
app/styles/app.scss
bower.json
ember-cli-build.js
tests/unit/models/channel-test.js

Render links in topics

---

app/components/message-chat/component.js
app/styles/app.scss
tests/unit/components/message-chat-test.js

Render links in messages

---

app/index.html
app/initializers/sockethub.js
config/environment.js
ember-cli-build.js
package.json
scripts/deploy.sh
scripts/update-version-file.sh
vendor/sh-assets-local.html
vendor/sh-assets-remote.html

I set up deployment to 5apps Deploy via scripts, using sockethub.kosmos.org in production. All working. Just waiting for DNS to propagate for https://hyperchannel.kosmos.org/

Deployment

---

app/models/base_channel.js
app/models/channel.js
app/models/space.js
app/models/user_channel.js
app/services/smt.js
config/environment.js
package.json

Refs #4 
This loads today's logs when joining a channel from the public Kosmos storage when available.
Also did some refactorings along the way.

Load today's channel logs

---

app/components/message-chat/component.js
app/styles/components/message-chat.scss
tests/unit/components/message-chat-test.js

(currently deployed to prod)
closes #23
connected to #23

Render images inline

---

app/controllers/application.js
app/routes/application.js
app/services/logger.js
app/services/smt.js
tests/unit/services/logger-test.js

I would propose something like that to close #67
Any feedback is welcome!

Feat(logger): Add a logger service

---

app/initializers/hammer.js

Bring back text selection

---

app/components/channel-nav/component.js
app/components/channel-nav/template.hbs
app/routes/application.js
app/styles/app.scss
app/templates/application.hbs

Adds a "+" link as last item of the channel nav and will transition/join a channel name given via prompt.

Join channels via sidebar link and prompt

---

app/components/channel-container/component.js
app/models/channel.js
app/services/smt.js

Paired with @skddc on this.
Fixes #89
Rename some variables to make a little more sense and use UTC dates everywhere.

Fix archive loading for today's logs

---

app/components/channel-container/component.js
app/components/message-chat-me/component.js
app/controllers/space/base_channel.js
app/models/space.js
app/routes/settings.js
app/routes/space/base_channel.js
app/services/coms.js
app/services/remotestorage.js
app/services/sockethub-irc.js
config/environment.js

This fixes some eslint warnings and removes code duplication, hopefully pleasing the code climate gods.

Refactorings

---

app/services/coms.js
app/services/sockethub-irc.js
app/services/sockethub-xmpp.js

* XMPP join method
* more separation from comms.js to the respective platforms

added xmpp function for joining

---

app/styles/app.scss

Refs #114
Don't show all the warnings in the console until we use an autoprefixer.

Silence the Bourbon deprecation messages

---

app/models/space.js
app/services/coms.js

Change username when getting update event from Sockethub

---

app/components/message-chat/component.js
app/styles/components/message-chat.scss
tests/unit/components/message-chat-test.js

Connected to #12 
I have used spans with classes, I'm open to other ways to do it though

Add support for bold and italic messages

---

app/components/message-chat/component.js
tests/unit/components/message-chat-test.js

Don't linkify email addresses

---

app/services/coms.js
app/services/sockethub-irc.js
tests/unit/services/coms-test.js

Fixes #118
This is the moment when the user is also shown as online to other clients.

Connect IRC channel after getting userlist

---

app/components/channel-container/template.hbs
app/styles/app.scss

Closes #131
Shows the title for a disconnected channel with lower opacity.

Indicate connection status in channel header

---

app/components/channel-container/component.js
app/components/channel-container/template.hbs
package-lock.json
package.json

Fixes #103
Using ember-concurrency prevents running the same task more than once at the same time.
The [ember-concurrency addon](http://ember-concurrency.com) is pretty
nice. Should be useful for a lot of other asynchronous tasks as well.

Fix duplicate archive message loading

---

app/components/channel-nav/component.js
app/models/space.js
package-lock.json
package.json
tests/unit/components/channel-nav-test.js

Closes #148
Ctrl+Shift+Down goes to next channel
Ctrl+Shift+Up goes to previous channel

Allow to switch channels via keyboard shortcuts

---

app/components/channel-container/component.js
app/routes/space/base_channel.js

Bug was introduced in bb5d011.

Fix hiding sidebar on mobile when switching channels

---

.github/release-drafter.yml
.travis.yml
package-lock.json
package.json

Let's introduce us some automated changelogs/release notes!
In order for the tests to pass, I had to update `ember-cli-sass` and revert to an older Sockethub on Travis.

Add release-drafter config; fix Sass and Sockethub deps

---

.template-lintrc.js
app/components/channel-container/template.hbs
app/routes/application.js
app/services/logger.js
app/services/sockethub-irc.js
app/services/sockethub-xmpp.js

Plus some template changes and fixing debug logs.
refs #184

Octanify logger service

---

app/styles/components/message-chat.scss

Prevent long words from breaking the layout

---

.travis.yml
app/models/space.js
app/services/coms.js
app/services/sockethub-irc.js
app/utils/channel-message-from-sockethub-object.js
config/space-presets.json
package-lock.json
package.json
tests/unit/models/space-test.js
tests/unit/services/coms-test.js
tests/unit/services/sockethub-irc-test.js
tests/unit/utils/channel-message-from-sockethub-object-test.js

Continuation of #181, but based on latest changes in Hyperchannel master.

Modifications for latest Sockethub

---

app/components/channel-container/template.hbs
app/controllers/application.js
app/controllers/space/base_channel.js
app/routes/space/channel.js
app/routes/space/channel/shares.js

Was really just a few lines of code in a route. No idea how we ended up there, but it looks to me like some prototyping leftovers got in the way accidentally.
fixes #211

Fix mobile sidebar issue

---

app/templates/space/user_channel.hbs

Fixes #214
This fixes a few undefined/not a function errors.

Add missing arguments to ChannelContainer for DM channel

---

.travis.yml
package-lock.json

Should be squashed when merged.
refs #227

Fix Travis CI builds

---

package-lock.json
package.json

* Use new release version of the kosmos module from npm
* Update rs.js

Update remoteStorage dependencies

---

app/components/channel-container/template.hbs

Most people are not able to change channel settings, so it's going to be more of an info tab than a settings one.

Change channel info/settings icon

---

app/components/account-list/template.hbs
app/components/add-chat-account-irc/template.hbs
app/components/add-chat-account-xmpp/template.hbs
app/components/channel-nav/component.js
app/components/join-channel-irc/component.js
app/components/join-channel-irc/template.hbs
app/components/join-channel-xmpp/component.js
app/components/join-channel-xmpp/template.hbs
app/components/join-channel/component.js
app/components/join-channel/template.hbs
app/components/message-input/component.js
app/components/message-input/template.hbs
app/controllers/application.js
package-lock.json
package.json
tests/integration/components/add-chat-account-xmpp/component-test.js
tests/integration/components/join-channel-irc/component-test.js
tests/integration/components/join-channel-xmpp/component-test.js
tests/integration/components/join-channel/component-test.js

Adds a basic new channel-join dialog with an account switcher and different components based on the chat protocol of the account.
Left to do:

UI for joining channels

---

app/services/sockethub-irc.js
app/services/sockethub-xmpp.js
package-lock.json
package.json

No need for an external dependency anymore.

Remove "extend" module in favor of modern JS

---

app/components/date-headline/template.hbs
app/components/message-chat/component.js
app/components/message-chat/template.hbs
app/helpers/html-safe.js
app/styles/components/message-chat.scss
package-lock.json
package.json
tests/integration/components/message-chat/component-test.js
tests/unit/components/message-chat-test.js

Adds avatar placeholder icons with the first letter of the message sender's nickname, and coloring them according to [XEP-0392](https://xmpp.org/extensions/xep-0392.html).

Add user avatar placeholders

---

.codeclimate.yml

Also increases the threshold on function LOC, because we regularly end up with just slightly over 25, but without the functions being too complex.

Update CodeClimate config to version 2

---

app/services/coms.js
app/services/sockethub-irc.js
app/services/sockethub-xmpp.js

Tested with and depending on https://github.com/sockethub/sockethub/pull/675
Should only be merged when the SH change is merged.

Replace Sockethub type "observe" with "query"

---

app/components/account-list/template.hbs
app/components/add-chat-account-irc/template.hbs
app/components/add-chat-account-xmpp/template.hbs
app/components/add-chat-account/template.hbs
app/components/channel-container/template.hbs
app/components/date-headline/template.hbs
app/components/flash-message-error/template.hbs
app/components/join-channel-xmpp/template.hbs
app/components/join-channel/template.hbs
app/components/message-chat/component.js
app/components/message-chat/template.hbs
app/styles/_buttons.scss
app/styles/_forms.scss
app/styles/_modals.scss
app/styles/app.scss
app/templates/add-account.hbs
app/templates/space/index.hbs
app/templates/welcome.hbs
config/tailwindcss-config.js
package-lock.json
package.json

* Update packages
* Update config
* Update flexbox class names
* Update color class names

Upgrade Tailwind CSS to version 3

---

app/components/account-list/template.hbs
app/components/add-chat-account-irc/component.js
app/components/add-chat-account-irc/template.hbs
app/components/add-chat-account-xmpp/component.js
app/components/add-chat-account-xmpp/template.hbs
app/components/button-submit/template.hbs
app/styles/_buttons.scss
tests/integration/components/button-submit/component-test.js

Add a button component with a loading spinner, which becomes disabled while loading things. Can be used anywhere in the app with custom classes and button text.
closes #271

Show loading indicator and disable submit button on connect

---

app/services/coms.js
app/services/sockethub-irc.js

This ended up being tiny, not sure if I hit all the handling but so far I've just had to really update to ignore service messages (these are messages from the IRC server that are not from any one room, and the UI doesn't have an interface for handling). Reference https://github.com/sockethub/sockethub/pull/684

Handle unified schema
