67P/hyperchannel

- app/components/channel-container/component.js
- app/components/channel-nav/template.hbs
- app/models/channel.js
- app/routes/space/base_channel.js
- app/routes/space/channel.js
- app/services/smt.js
- app/styles/app.scss
- app/styles/components/channel-nav.scss
- tests/unit/models/channel-test.js
This adds a visibility status to channels, and marks them as unread when new messages arrive, while they're not visible.
Connected to #46
> Unread status for channels

- app/styles/_layout.scss
- bower.json
Connected to #63
I created an intermittent patched version of hammer.js that fixed our swiping problem in mobile Chrome. I got that fix from the original issue discussion. Apparently it breaks pan support in desktop Chrome, but since we are not using that I think that's ok for now.
I'll keep an eye on the original issue to see when they found a proper fix for it.
While at it I also enabled momentum scrolling for mobile Safari. Feels much nicer.
> Fix swiping in Chrome

- bower.json
- ember-cli-build.js
This keeps the top menu at it's place when scrolling all the way up to the top.
> Don't bounce when scrolling to top or bottom on mobile Safari

- .jshintrc
- config/environment.js
- package.json
- vendor/sh-assets-local.html
- vendor/sh-assets-remote.html
This adds `broccoli-serviceworker`, which automatically generates a `ServiceWorker` file and registration for the Ember app assets (cache-first) and the Sockethub assets (network-first). Configuration is in `config/environment.js`.
We'll need our own SW code for Push notifications and more sophisticated cash handling (e.g. for Sockethub assets), of course, so this is meant mostly for loading time improvements in production for now.
<del>Caveat: This branch only works with https://github.com/sockethub/sockethub/pull/204 because the current Sockethub master doesn't add CORS headers to the static asset responses.</del> PR has been merged. So latest `master` should work.
> Add ServiceWorker for offline assets

- app/services/smt.js
Completely missed when implementing #83 that, now that we have a list of logged channels, we don't need to try to load any archive when joining an unlogged channel :)
> Don't try to load archive when joining unlogged channel

- app/components/message-chat/component.js
- tests/unit/components/message-chat-test.js
I saw a talk about Ember security yesterday. One of the suggestions was to always use `noopener` and `noreferrer` as values for the `rel` attribute of links with target `_blank` to prevent a possible XSS vulnerability.
> Add noopener and noreferrer to links with target _blank

- app/components/channel-nav/template.hbs
- app/controllers/space/base_channel.js
- app/models/space.js
- app/routes/application.js
- app/services/remotestorage.js
- app/services/smt.js
- tests/unit/models/space-test.js
The channels were only persisted when joining via the `/join` command, but not when using the + from the menu. I moved the persisting to the method that both the features use.
Also, when leaving channels, the two properties `channels` and `channelList` of the `Space` model diverted. This prevented the channels from being removed from remoteStorage. I changed the list of channel names to be a computed property based on the actual list of channels instead.
> Fix persisting of joined channels in remoteStorage

- app/services/coms.js
- app/services/sockethub-irc.js
Closes #84
When getting a channel update message from Sockethub for a channel that didn't exist in Hyperchannel yet (happens when using the app in two tabs or two different browsers), it was creating the channel with the full id instead of just the name.
> Fix channel creation from updateChannelTopic method

- .jshintrc
- app/styles/_layout.scss
- app/styles/app.scss
- app/styles/components/date-headline.scss
- ember-cli-build.js
- package.json
This switches some of Bourbon's deprecated mixins to normal syntax, for
which prefixes are added by postcss/autoprefixer instead.
connected to #114
closes #114
> Use postcss and autoprefixer, remove old bourbon mixins

- app/routes/space/base_channel.js
Fixes #122
When there are multiple spaces, switching channels still kept the channel of the second space marked as visible, preventing the highlight when new messages arrived for that channel.
> Mark channels of all spaces as invisible when switching

- config/environment.js
- package-lock.json
- package.json
This updates the ServiceWorker-related deps and enables SW in development. It actually works just fine in FF in development, but not with the hosted version. I'll investigate what's wrong on the 5apps side of things, but it doesn't look like a bug in the plugin. Even more so, because nobody else reported it on the plugin source repo.
refs #80
> Update SW deps, use SW in dev

- app/components/channel-container/component.js
Fixes #133
Defining an empty swipe handler on the #channel-content causes the handler on the app container component to be triggered again. Seems to be a bug on elements that have "overflow-y: auto" set, which prevents the event to be triggered otherwise.
> Fix swipe events in Chrome

- app/styles/_layout.scss
- app/styles/components/message-chat.scss
The PR adds `overflow: auto` to `#channel` and `main` and `overflow-wrap: break-word` to `#channel` to make it work on mobile.
As a side effect we can remove the `.chat-message a` wrap rules.
> Fix overflow problems on mobile

- app/services/coms.js
- app/services/sockethub-xmpp.js
Closes #127 
This queries for the room attendance list when joining a new room and handles the corresponding response from Sockethub.
It needs the implementation for Sockethub XMPP platform, which I created a PR for at sockethub/sockethub-platform-xmpp#15
Right now this only seems to work properly when connected to XMPP alone, but not when also connected to IRC. I think this is related to the issue reported at sockethub/sockethub-platform-irc#22, in which @skddc already suspected it might not just be an IRC issue but a general multiple connections issue.
> Handle channel user list for XMPP

- app/components/channel-container/component.js
- app/components/channel-container/template.hbs
- app/components/message-chat/component.js
- app/components/message-chat/template.hbs
- tests/unit/components/channel-container-test.js
This prefixes the new message in the message input field with a username, when the username of a channel message is clicked/tapped.
That makes it easy to reply to people, without having to type their username first. Especially useful on touch devices, but also nice on laptops.
> Easy username mentions

- vendor/sh-assets-remote.html
Refs #161
Newer versions of SocketHub don't provide an unminified version of activity-streams.js anymore.
So until sockethub/sockethub#237 is fixed, we use the minified version.
> Use new URL for activity-streams lib

- app/components/channel-container/template.hbs
- app/components/scrolling-observer/component.js
- app/components/user-list/component.js
- app/components/user-list/template.hbs
Closes #163
To improve the performance when switching to channels with a lot of users, only a subset of the users is rendered at first. More users will be rendered, when scrolling to the bottom of the list.
> Use partial rendering for large user lists

- app/components/channel-container/component.js
- app/components/channel-container/template.hbs
- app/components/scrolling-observer/component.js
Closes #92
This displays only the last 30 messages when opening a channel to improve the rendering speed. More messages are then displayed when scrolling up to the top of the page.
This PR is a replacement for #162 and should fix all the remaining problems that PR still had.
The code is also much cleaner/simpler. It uses the scrolling-observer component introduced in #166 both for rendering more messages when scrolling up, as well as enabling/disabling automatic scrolling when scrolling down.
> Partial message rendering

- .travis.yml
Getting emails from Travis everytime you push is pretty annoying.
This deactivates email notifications for successful builds, so you only get notified when a build fails.
> Don't send emails for successful Travis builds

- app/components/scrolling-observer/component.js
This fixes an exception "Trying to call set on a destroyed object" when switching between a user channel and a group chat channel.
> Disconnect IntersectionObserver when destroying component

- app/controllers/space/base_channel.js
- app/services/sockethub-irc.js
- app/utils/channel-message-from-sockethub-object.js
Closes #117
This change makes sure that your own messages are also shown when having the app open in another tab, window or browser.
It also fixes a bug of a missing date headline when writing the first message of the day in a channel
> Show own messages in different windows.

- app/services/remotestorage.js
- package-lock.json
- package.json
This gets rid of the last remaining deprecation warning. Also the import syntax is nicer :)
> Replace ember-browserify with ember-auto-import

- app/components/channel-container/template.hbs
- app/components/message-input/component.js
- app/components/message-input/template.hbs
Closes #26
Just write the first letter(s) of a username and hit tab.
When the name is completed at the beginning, a colon is added after the name.
This doesn't support cycling through names when there are multiple users with the same prefix yet. I'll create a separate issue for it.
> Add username completion

- app/components/channel-container/template.hbs
- app/components/link-to-username/component.js
- app/styles/_colors.scss
- app/styles/_layout.scss
- app/styles/app.scss
- app/styles/components/channel-container.scss
- app/styles/vendor/_include_media.scss
* Make the channel's nav part of the channel header, so it is independent of the sidebar
* Use flexbox layout for the channel header
* Show channel nav on mobile (prep for new content sidebars)
* Fix long channel topics breaking the layout (use ellipsis for overflow)
* Make channel topic less opaque until hovering it
fixes #51
> Refactor layout

- .template-lintrc.js
- app/components/channel-container/component.js
- app/components/channel-container/template.hbs
- app/components/channel-nav/component.js
- app/components/channel-nav/template.hbs
- app/components/message-input/component.js
- app/components/message-input/template.hbs
- app/templates/application.hbs
- package-lock.json
- package.json
- tests/helpers/create-component.js
- tests/unit/components/channel-nav-test.js
Needed to fork ember-keyboard-shortcuts to add Octane support.
Unit tests are not generally a thing for Glimmer components, and I think ours should actually be rewritten as acceptance tests. But to make it work for now, I used the solution described in
https://timgthomas.com/2019/11/unit-testing-glimmer-components/
refs #184
> Octanify channel-nav, message-input

- app/styles/app.scss
- app/styles/components/channel-container.scss
- app/styles/components/channel-nav.scss
- app/styles/components/message-input.scss
* Use ellipsis for long channel names in channel nav
* Use text cursor instead of pointer for message input
> UI enhancements

- .template-lintrc.js
- app/components/app-container/component.js
- app/components/channel-container/template.hbs
- app/components/user-list/template.hbs
- app/controllers/space/base_channel.js
- app/controllers/space/channel/index.js
- app/router.js
- app/routes/space/base_channel.js
- app/routes/space/channel.js
- app/routes/space/channel/index.js
- app/routes/space/channel/settings.js
- app/routes/space/channel/shares.js
- app/styles/_layout.scss
- app/styles/_mixins.scss
- app/styles/app.scss
- app/styles/components/channel-container.scss
- app/styles/components/user-list.scss
- app/templates/space/channel.hbs
- app/templates/space/channel/index.hbs
- app/templates/space/channel/settings.hbs
- app/templates/space/channel/shares.hbs
- tests/unit/controllers/space/channel/index-test.js
- tests/unit/routes/space/channel/index-test.js
- tests/unit/routes/space/channel/settings-test.js
- tests/unit/routes/space/channel/shares-test.js
Makes channel sidebar content routable via channel subroutes, and adds header styles and dummy content. Also introduces wide sidebars for tabs with more content.
The sidebars work slightly different on desktop and mobile, as they're optimized for the available screen real estate.
> Channel sidebar tabs/content

- app/components/channel-nav/template.hbs
- app/models/base_channel.js
- app/models/space.js
- app/styles/_layout.scss
- app/styles/components/channel-nav.scss
- package-lock.json
- package.json
- tests/unit/models/channel-test.js
- tests/unit/models/space-test.js
* Show user address instead of space name
* Group channels by MUC domain
* Show short channel name instead of full JID. Add a hash so they look familiar (like IRC and Slack channels)
> Improve channel list/nav for XMPP spaces

- app/components/channel-container/component.js
- app/components/channel-container/template.hbs
- app/components/scrolling-observer/component.js
- app/components/scrolling-observer/template.hbs
- app/components/user-list/component.js
- app/components/user-list/template.hbs
Fixes #202
After the Octane upgrade, all observers were broken. Replacing them with render modifiers fixed the issues and also removed the last remaining deprecation warnings.
The ScrollingObserver component doesn't use any Ember observers anymore, but still contains the word "observer". So I had to add an ESLint config line to ignore the "ember/no-observers" rule to the component.js file.
> Replace Ember observers with render modifiers

- app/components/date-headline/template.hbs
Fixes #207
The markup structure was mixed up when migrating the component to a Glimmer component.
> Fix date-headline markup

- app/services/coms.js
- app/services/remotestorage.js
Required a fix for the RS module, so you'll have to delete the node module and `npm i` again to have this one working: https://github.com/67P/remotestorage-module-kosmos/commit/ec6bb0b2ba602cc238728c02b5decdb95ae6b503
refs #227
> Remove channel from storage when leaving

- app/components/add-chat-account-irc/component.js
- app/components/add-chat-account-irc/template.hbs
- app/models/base_channel.js
- app/routes/application.js
- app/services/coms.js
- app/services/local-data.js
- app/services/sockethub-irc.js
* Add component for setting up IRC accounts
* Adapt IRC sockethub service and other relevant code for the new data model
* Fix some small things
Note:
* DMs are still disabled in the UI for now
* There's some commented code to implement when Sockethub implements a connect command for IRC (currently being done automatically on channel joins).
> Refactor spaces to accounts/channels for IRC

- README.md
- app/components/message-chat/component.js
- app/components/message-chat/template.hbs
- app/controllers/base_channel.js
- app/models/base_channel.js
- app/models/message.js
- app/services/sockethub-xmpp.js
- app/styles/components/message-chat.scss
- tests/fixtures/accounts.js
- tests/unit/services/sockethub-xmpp-test.js
This marks outgoing messages as pending, and then confirms that they were sent when received back from the room. It also fixes the problem of one's own messages missing in the chat history that is sent by XMPP servers upon joining a channel.
<del>Note: will probably fail with DMs (#242), because we would need message carbons for those. Hence the WIP, until DMs are merged.</del> Fixed for DMs.
---
P.S.: I think we'll want to have a timeout for showing messages as pending in the UI later on. Currently, there's a bit of a flash from switching the text color after a split second. And we can also add an actual text marker or other indicator, after a few seconds of it not having confirmed.
> Pending status for outgoing XMPP messages

- app/services/coms.js
- app/services/sockethub-irc.js
- app/services/sockethub-xmpp.js
Closes #239
During testing I noticed that Sockethub actually sends "online" presence updates for incoming "unavailable" stanzas. I've created an issue for that at https://github.com/sockethub/sockethub/issues/564.
This PR also deletes the creation of the ActivityStream object when leaving an IRC room, because I confirmed that it's not needed.
> Send and handle leave messages for XMPP MUC

- app/routes/application.js
Triggering a transition from the beforeModel method in the application route will cause the beforeModel method to be called again on the next transition. Moving the transition call to the redirect method fixes this.
> Fix redirects causing duplicate setup method calls

- app/components/join-channel-xmpp/template.hbs
- tests/integration/components/join-channel-irc/component-test.js
- tests/integration/components/join-channel-xmpp/component-test.js
This also changes the comment style of the commented code in the `join-channel-xmpp` component to fix the linter errors about HTML comments.
After merging #254 should be all green.
> Integration tests for join-channel-* components

- app/services/sockethub-xmpp.js
- tests/unit/services/sockethub-xmpp-test.js
Was not consistent with incoming AS messages.
Works with the latest commit in sockethub/sockethub#653.
> Fix outgoing message correction property name

- app/components/date-headline/template.hbs
- app/components/message-chat/component.js
- app/components/message-chat/template.hbs
- app/helpers/html-safe.js
- app/models/base_channel.js
- app/models/message.js
- app/styles/components/message-chat.scss
- package-lock.json
- package.json
- tests/integration/components/message-chat/component-test.js
- tests/unit/components/message-chat-test.js
- tests/unit/models/base-channel-test.js
Doesn't render every line of chat with all metadata, when the message is from the same user and in reasonably quick succession to the previous message.
I used 120 seconds as a cutoff for groupings. Not sure if that's too much already.
(The UI will be much nicer than this, and it will be even easier for the brain to parse messages belonging together, when we add avatars (with placeholders) soon.)
> Grouped chat messages

- .travis.yml
- app/components/add-chat-account-xmpp/component.js
- app/services/coms.js
- app/services/sockethub-irc.js
- app/services/sockethub-xmpp.js
- release/index.html
- vendor/sh-assets-local.html
- vendor/sh-assets-remote.html
I started testing the sockethub refactor (https://github.com/sockethub/sockethub/pull/596) with hyperchannel, and managed to fix a few things, however couldn't figure out how the join process was supposed to work after the connect (the connect works, just nothing is joined afterward).
Would be up to either pair with someone on finishing this, or if you just want to use this as an example branch and make a new PR that's fine with me too. The most important part to get started is to make sure you remove the <script> tags which include activity-streams.js as that's now a part of the sockethub-client.js
> Adapt code to new Sockethub Client API

- app/components/message-chat/component.js
- app/components/message-chat/template.hbs
- app/services/sockethub-xmpp.js
- app/styles/components/message-chat.scss
- config/tailwindcss-config.js
- tests/unit/components/message-chat-test.js
This makes the height of the document predictable before the images are loaded, so we can scroll to the end consistently.
(Auto-scrolling fixes coming up in a separate PR.)
refs #222
> Use fixed height for images, improve sizing

- app/services/sockethub-xmpp.js
`username` is now called `userAddress`, since https://github.com/sockethub/sockethub/pull/674 entered SH master.
> Update to new XMPP credentials schema

- app/components/add-chat-account-irc/component.js
- app/components/add-chat-account-xmpp/component.js
- app/services/sockethub-irc.js
- app/services/sockethub-xmpp.js
Implements and relies on https://github.com/sockethub/sockethub/pull/671
closes #194
> Use new Sockethub IRC connect flow, show connect errors

- app/components/add-chat-account-irc/component.js
- app/components/add-chat-account-irc/template.hbs
- app/models/account.js
- app/services/sockethub-irc.js
- package-lock.json
- package.json
For now, we just assume that all authenticated connections use SASL.
I was able to use this to successfully connect to Libera from my VPN, which they require SASL for. :tada: 
Tested with and depends on https://github.com/sockethub/sockethub/pull/673. Also required adding the `sasl` property to the RS module's schema (already published as 2.2.0).
closes #240
> Add SASL authentication for IRC

- app/services/logger.js
- app/services/remotestorage.js
Removes obsolete contexts, adds one for storage. RS actions are now logged via the service instead of `console.debug`.
> Clean up logging service, add storage context

- jsconfig.json
This adds mappings for paths to help editors resolve import statements to app and test files
Example:
```js
import Message from 'hyperchannel/models/message';
```
There is no actual `hyperchannel/` folder, those files are located in `app/` instead. This is what the config maps.
It gives us _jump to definition_ and _auto-import_ for functions defined within our own codebase for editors that support this.
Also the `exclude` attribute tells the language service what files are not part of the app's source code. This should help with  performance for IntelliSense/code completion.
After updating to a newer Ember version, we can also include Ember's type packages so we also get auto-import and code completion for Ember itself.
> Add some configs for better editor/language server support
